#!/bin/bash

if [ -z "$GITHUB_REF" ]
then
  echo "GITHUB_REF not set"
  exit 1
fi

if [[ $GITHUB_REF =~ ^refs\/heads\/ ]]; then
  echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
else 
  echo ::set-output name=branch::
fi

if [[ $GITHUB_REF =~ ^refs\/tags\/ ]]; then
  echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
else
  echo ::set-output name=tag::
fi