name: Check Package Versions

on:
  pull_request:
    branches:
      - develop

jobs:
  check:
    name: Run Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch entire git history

      - name: Determine if package verisons need to be updated
        uses: smartcontractkit/simple-module-versioner@develop
        with:
          mode: version
          folders: styleguide tools/redux tools/local-storage tools/ts-helpers tools/json-api-client
