name: Continuous Integration Workflow

on: [push]

env:
  CACHE_VERSION: 9c3bfa173ea0aca1f9939f8896feb4a5

jobs:
  integration:
    name: Integration tests
    runs-on: self-hosted
    strategy:
      matrix:
        test: ['test', 'test:ts']
        geth: [false]
        explorer: ['latest'] # TODO: add in 'develop' once image is published
    env:
      GETH_MODE: ${{ matrix.geth }}
      CI: true
      CHAINLINK_DB_NAME: postgres
      EXPLORER_DOCKER_TAG: ${{ matrix.explorer }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Run tests
        run: cd ./tools/docker && timeout --foreground 1200s ./compose ${{ matrix.test }}
      - name: Store logs artifacts
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: ./tools/docker/logs
